using FluentValidation;

namespace ChangeMe.Modules.Events.Application.SingleEvent.GetSingleEvent;

// TODO: Look at all validators because all was generated by ChatGPT
internal class GetSingleEventQueryValidator : AbstractValidator<GetSingleEventQuery>
{
    public GetSingleEventQueryValidator()
    {
        RuleFor(x => x.SingleEventId)
            .NotEmpty().WithMessage("Single event ID must not be empty.");
    }
}